Repository ImJaeOne/found, pull requests merged in 2025-03, with the labels that each got.

#5 Feat/#2 layout
  public/images/found_default_profile01.png
  public/images/found_default_profile02.png
  public/images/found_default_profile03.png
  public/images/found_default_profile04.png
  public/images/found_default_profile05.png
  public/images/found_default_profile06.png
  public/images/found_logo.png
  public/images/found_main01.jpg
  public/images/found_main02.jpg
  public/images/found_main03.jpg
  src/app/(layout)/Header.tsx
  src/app/layout.tsx
  src/constants/constants.js
Labels: ✨ Feature, 🎨 Html&css, 😇 재원

#7 Shadcn 컴포넌트 설치
  components.json
  package.json
  pnpm-lock.yaml
  src/app/globals.css
  src/ui/shadcn/avatar.tsx
  src/ui/shadcn/button.tsx
  src/ui/shadcn/calendar.tsx
  src/ui/shadcn/card.tsx
  src/ui/shadcn/carousel.tsx
  src/ui/shadcn/checkbox.tsx
  src/ui/shadcn/dialog.tsx
  src/ui/shadcn/input.tsx
  src/ui/shadcn/label.tsx
  src/ui/shadcn/popover.tsx
  src/ui/shadcn/switch.tsx
  src/ui/shadcn/tabs.tsx
  src/ui/shadcn/textarea.tsx
  src/utils/lib/cn.ts
  tailwind.config.ts
Labels: ⚙ Setting, 🫡 종욱

#16 Feat/#12 Chatting & MyPage 공통 컴포넌트 제작
  src/ui/common/SectionHeader.tsx
Labels: ✨ Feature, 🎨 Html&css, 😇 재원

#15 Feat/#13 공통 컴포넌트 UserProfile 레이아웃 구현
  package.json
  pnpm-lock.yaml
  src/app/mypage/page.tsx
  src/ui/common/UserProfile.tsx
  tailwind.config.ts
Labels: ✨ Feature, 🎨 Html&css, 🧸 주하

#19 Feat/#4 Login/Signup 로직 구현
  package.json
  pnpm-lock.yaml
  src/app/login/page.tsx
  src/app/sign/_components/AuthForm.tsx
  src/app/sign/login/page.tsx
  src/app/sign/signup/page.tsx
  src/app/signup/page.tsx
  src/constants/auth.js
  src/constants/constants.js
  src/services/client.ts
  src/services/server.ts
  src/services/supabaseClient.ts
  src/types/users.ts
Labels: ✨ Feature, 🐻 민경

#18 Feat/#10 userCardList 컴포넌트 제작
  src/app/matelist/_components/UserCard.tsx
  src/app/matelist/_components/UserCardList.tsx
  src/app/matelist/page.tsx
  src/constants/constants.js
Labels: 🎨 Html&css, 🍔 지수

#17 Feat/#8 user card 컴포넌트 제작
  src/app/matelist/_components/UserCard.tsx
Labels: 🎨 Html&css, 🍔 지수

#21 Feat/#9 chatting component layout 구현
  package.json
  pnpm-lock.yaml
  src/app/chatting/_components/Chatting.tsx
  src/app/chatting/_components/MessageCard.tsx
  src/app/chatting/page.tsx
  src/ui/common/SectionHeader.tsx
  tailwind.config.ts
Labels: ✨ Feature, 🎨 Html&css, 😇 재원

#32 Refactor/#20 auth refactor
  package.json
  pnpm-lock.yaml
  src/app/layout.tsx
  src/app/sign/_components/AuthForm.tsx
  src/app/sign/login/page.tsx
  src/app/sign/signup/page.tsx
  src/constants/constants.js
  src/constants/users.js
  src/hooks/useToast.ts
  src/services/usersServices.ts
  src/types/users.ts
  src/ui/shadcn/toast.tsx
  src/ui/shadcn/toaster.tsx
Labels: 🔨 Refactor, 🐻 민경

#30 Feat/#29 Input 공통 컴포넌트 구현
  pnpm-lock.yaml
  src/ui/common/CommonInput.tsx
  src/ui/shadcn/input.tsx
  src/ui/shadcn/textarea.tsx
Labels: ✨ Feature, 🎨 Html&css, 😇 재원

#33 Feat/#22 appointment layout
  src/app/@modal/(.)appointment/_components/AppointmentSpan.tsx
  src/app/@modal/(.)appointment/_components/DatePickerDemo.tsx
  src/app/@modal/(.)appointment/page.tsx
  src/app/@modal/default.tsx
  src/app/chatting/_components/Chatting.tsx
  src/app/chatting/_components/SectionHeader.tsx
  src/app/chatting/page.tsx
  src/app/layout.tsx
  src/constants/constants.js
  src/hooks/useClickOutside.ts
  src/hooks/useFindAddress.ts
  src/types/appointments.ts
  src/ui/common/CommonInput.tsx
Labels: ✨ Feature, 🎨 Html&css, 😇 재원

#34 Refactor/#20 AuthForm 리팩토링
  src/app/sign/_components/AuthForm.tsx
  src/hooks/useAuthContents.ts
  src/hooks/useAuthValidation.ts
Labels: 🔨 Refactor, 🐻 민경

#39 Fix#31 메인 버튼 left 변경 /아바타 변경
  src/app/_components/MainCarousel.tsx
  src/ui/shadcn/avatar.tsx
  src/ui/shadcn/button.tsx
Labels: 🔨 Refactor, 🫡 종욱

#40 Feat/#6 마이페이지 컴포넌트 제작
  src/app/mypage/_components/AppointmentCard.tsx
  src/app/mypage/_components/Appointments.tsx
  src/app/mypage/_components/SectionHeader.tsx
  src/app/mypage/page.tsx
Labels: ✨ Feature, 🎨 Html&css, 🧸 주하

#41 Feat/#13 UserProfile 컴포넌트 리팩토링
  src/ui/common/UserProfile.tsx
Labels: 🔨 Refactor, 🧸 주하

#44 Style/#38 로그인/회원가입 페이지 + AuthForm 컴포넌트 디자인
  src/app/@modal/(.)appointment/page.tsx
  src/app/sign/_components/AuthForm.tsx
  src/app/sign/login/page.tsx
  src/app/sign/signup/page.tsx
  src/hooks/useAuthValidation.ts
  src/ui/common/CategorySeletor.tsx
  src/ui/common/CommonInput.tsx
  src/ui/shadcn/input.tsx
Labels: 🎨 Html&css, 🐻 민경

#49 Bugfix/ CommonInput와 react-hook-form 연동 안되는 문제 해결
  src/ui/common/CommonInput.tsx
Labels: 🐞 BugFix, 🐻 민경

#51 Feat/#43 address component 분리
  src/app/@modal/(.)appointment/_components/DatePickerDemo.tsx
  src/app/@modal/(.)appointment/page.tsx
  src/hooks/useAddressChange.ts
  src/ui/common/AddressInput.tsx
  src/ui/common/CommonInput.tsx
Labels: ✨ Feature, 🔨 Refactor, 🐻 민경

#53 Feat/#43 주소 input 공통 컴포넌트 구현
  src/app/@modal/(.)appointment/page.tsx
  src/app/sign/_components/AuthForm.tsx
  src/hooks/useAddressChange.ts
  src/hooks/useAuthValidation.ts
  src/hooks/useFindAddress.ts
  src/services/usersServices.ts
  src/types/users.ts
  src/ui/common/AddressInput.tsx
Labels: ✨ Feature, 🔨 Refactor, 🐻 민경

#56 Feat/#35 실시간 채팅
  package.json
  pnpm-lock.yaml
  src/app/chatting/[id]/page.tsx
  src/app/chatting/_components/ ChattingUserProfile.tsx
  src/app/chatting/_components/Chatting.tsx
  src/app/matelist/_components/UserCard.tsx
  src/app/mypage/page.tsx
  src/providers/RQProviders.tsx
  src/services/server.ts
  src/types/chats.ts
  src/types/params.ts
  src/ui/common/UserProfile.tsx
Labels: 📬 API, ✨ Feature, 😇 재원

#58 🩹 Fix: ChattingUserProfile.tsx 공백 수정 #57
  src/app/chatting/[id]/page.tsx
  src/app/chatting/_components/ChattingUserProfile.tsx
Labels: 🐞 BugFix, 😇 재원

#61 Fix/#59 실시간 채팅 공유 문제
  src/app/chatting/_components/Chatting.tsx
Labels: 📬 API, 🐞 BugFix, 😇 재원

#60 Feat/#24 mateList 기본적인 구현
  src/app/api/categories/route.ts
  src/app/api/users/route.ts
  src/app/matelist/_components/UserCard.tsx
  src/app/matelist/_components/UserCardList.tsx
  src/app/matelist/_components/UserCardListContainer.tsx
  src/app/matelist/page.tsx
  src/hooks/useGoChatting.ts
  src/services/getServices.ts
Labels: 📬 API, 🐞 BugFix, ✨ Feature, 🎨 Html&css, 🍔 지수

#66 Feat/#54 Zustand로 로그인한 유저 상태관리
  package.json
  pnpm-lock.yaml
  src/app/layout.tsx
  src/hooks/useAuthValidation.ts
  src/providers/AuthProvider.tsx
  src/services/userStore.ts
  src/services/usersServices.ts
  src/types/users.ts
Labels: ✨ Feature, 🐻 민경

#68 Bugfix/#67 Zustand Provider 오류 발생
  src/providers/AuthProvider.tsx
  src/services/userStore.ts
Labels: 🐞 BugFix, 🐻 민경

#71 Feat/#65 로그인 여부에 따른 Header 조건부 렌더링
  src/app/(layout)/Header.tsx
  src/app/(layout)/HeaderNav.tsx
  src/app/_components/MainCarousel.tsx
  src/app/layout.tsx
  src/hooks/useAuthValidation.ts
  src/services/usersServices.ts
  src/ui/shadcn/toast.tsx
Labels: ✨ Feature, 🎨 Html&css, 🐻 민경

#75 Feat/#70 middleware
  middleware.ts
  src/app/matelist/page.tsx
  src/services/middleware.ts
  src/services/server.ts
  src/services/usersServices.ts
Labels: 📬 API, ✨ Feature, 🍔 지수

#79 Refactor/#72 Appointment 생성 컴포넌트 리팩토링
  src/app/@modal/(.)appointment/[id]/page.tsx
  src/app/@modal/(.)appointment/_components/DatePickerDemo.tsx
  src/app/appointment/[id]/page.tsx
  src/app/appointment/_components/AppointmentForm.tsx
  src/app/sign/_components/AuthForm.tsx
  src/constants/appointment.js
  src/constants/constants.js
  src/hooks/useAddressChange.ts
  src/hooks/useAppointmentContents.ts
  src/hooks/useAppointmentValidation.ts
  src/hooks/useAuthValidation.ts
  src/hooks/useFindAddress.ts
  src/services/appointmentServices.ts
  src/types/appointments.ts
  src/ui/common/AddressInput.tsx
  src/ui/common/CategorySeletor.tsx
  src/ui/common/CommonInput.tsx
Labels: 🔨 Refactor, 🐻 민경

#81 Feat/#50 component userprofile
  next.config.mjs
  src/app/matelist/_components/UserCard.tsx
  src/app/matelist/_components/UserCardList.tsx
  src/app/mypage/[id]/[appointment-id]/page.tsx
  src/app/mypage/[id]/page.tsx
  src/app/mypage/_components/AppointmentCard.tsx
  src/app/mypage/_components/Appointments.tsx
  src/app/mypage/_components/ProfileDialog.tsx
  src/app/mypage/_components/UserProfile.tsx
  src/app/mypage/page.tsx
  src/constants/constants.js
  src/hooks/mutations/useEditProfileMutation.ts
  src/hooks/mutations/useUploadImageMutation.ts
  src/hooks/queries/useAppointmentQuery.ts
  src/hooks/queries/useUserQuery.ts
  src/hooks/useAuthValidation.ts
  src/services/appointmentServices.ts
  src/services/profileServices.ts
  src/services/uploadProfile.ts
  src/services/userStore.ts
  src/types/appointments.ts
  src/types/image.ts
  src/types/users.ts
  src/ui/common/UserProfile.tsx
  src/ui/shadcn/button.tsx
  src/ui/shadcn/dialog.tsx
  src/ui/shadcn/switch.tsx
Labels: 🐞 BugFix, ✨ Feature, 🔨 Refactor, 🧸 주하, 🫡 종욱

#85 🩹 Fix: serverSupabase 삭제 #84
  src/services/usersServices.ts
Labels: 🐞 BugFix, 😇 재원

#83 Feat/#80 소셜 로그인 구현
  next.config.mjs
  src/app/(layout)/Header.tsx
  src/app/(layout)/HeaderNav.tsx
  src/app/layout.tsx
  src/app/mypage/_components/Appointments.tsx
  src/app/mypage/_components/UserProfile.tsx
  src/app/sign/_components/AuthForm.tsx
  src/providers/AuthListener.ts
  src/services/socialServices.ts
Labels: ✨ Feature, 🐻 민경

#86 Feat/#50 mypage 리팩토링
  src/app/mypage/_components/AppointmentCard.tsx
  src/app/mypage/_components/ProfileDialog.tsx
  src/app/mypage/_components/UserProfile.tsx
  src/constants/my-page.js
  src/services/appointmentServices.ts
Labels: 🐞 BugFix, ✨ Feature, 🎨 Html&css, 🔨 Refactor, 🧸 주하, 🫡 종욱

#90 Bugfix/#88 일반 회원가입시 사용자 입력값이 아닌 디폴트 값으로 입력되는 오류 해결
  src/app/chatting/_components/Chatting.tsx
  src/app/chatting/_components/MessageCard.tsx
  src/providers/AuthListener.ts
  src/services/userStore.ts
  src/services/usersServices.ts
Labels: 📬 API, 🐞 BugFix, 🎨 Html&css, 🐻 민경

#91 Feat#50 mypage 변경
  package.json
  pnpm-lock.yaml
  src/app/mypage/[id]/page.tsx
  src/app/mypage/_components/AppointmentCard.tsx
  src/app/mypage/_components/Appointments.tsx
  src/app/mypage/_components/ProfileDialog.tsx
  src/app/mypage/_components/SectionHeader.tsx
  src/app/mypage/_components/UserProfile.tsx
  src/constants/my-page.js
Labels: 🐞 BugFix, ✨ Feature, 🎨 Html&css, 🔨 Refactor, 🧸 주하, 🫡 종욱

#93 Feat/#74 appointment subscribe
  src/app/@modal/(.)appointment/[id]/page.tsx
  src/app/@modal/(.)appointment/_components/AppointmentModal.tsx
  src/app/@modal/(.)appointment/_components/ConfirmedAppointment.tsx
  src/app/appointment/[id]/page.tsx
  src/app/appointment/_components/AppointmentForm.tsx
  src/app/chatting/_components/Chatting.tsx
  src/app/chatting/_components/MessageCard.tsx
  src/hooks/mutations/useAppointmentMutation.ts
  src/hooks/queries/useAppointmentQuery.ts
  src/hooks/useAppointmentValidation.ts
  src/hooks/useAuthValidation.ts
  src/services/appointmentServices.ts
  src/services/chatsServices.ts
  src/types/appointments.ts
  src/ui/common/AddressInput.tsx
Labels: 📬 API, ✨ Feature, 😇 재원

#100 Docs/#97 README 작성 및 메타데이터 추가
  README.md
  public/images/ERD.png
  src/app/sign/login/page.tsx
  src/app/sign/signup/page.tsx
Labels: 📃 Docs, ✨ Feature, 🐻 민경

#99 Feat/#50 마이페이지 약속 필터링 및 프로필 변경 시 zustand 동기화
  src/app/mypage/[id]/page.tsx
  src/app/mypage/_components/Appointments.tsx
  src/app/mypage/_components/ProfileDialog.tsx
  src/app/mypage/_components/UserProfile.tsx
  src/services/appointmentServices.ts
  src/services/userStore.ts
  src/services/usersServices.ts
Labels: 🔨 Refactor, 🧸 주하, 🫡 종욱

#102 Refactor/#95 matelist chatting refactor
  next.config.mjs
  public/images/favicon.ico
  src/app/@modal/(.)appointment/[id]/page.tsx
  src/app/@modal/(.)appointment/_components/ConfirmedAppointment.tsx
  src/app/appointment/[id]/page.tsx
  src/app/appointment/_components/AppointmentForm.tsx
  src/app/chatting/[id]/page.tsx
  src/app/chatting/_components/UserProfile.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/app/matelist/_components/AuthCardList.tsx
  src/app/matelist/_components/CategoryCardSection.tsx
  src/app/matelist/_components/UserCard.tsx
  src/app/matelist/_components/UserCardList.tsx
  src/app/matelist/_components/UserCardListContainer.tsx
  src/app/matelist/page.tsx
  src/hooks/queries/useChatQuery.ts
  src/hooks/queries/useUserQuery.ts
  src/hooks/useSubscribeChat.ts
Labels: 🔨 Refactor, 😇 재원
